config/routes.rb
class AdminRestriction
  def matches?(request)
    # user_id = request.env['rack.session'][:user_id]
    auth_token = request.env['rack.request.cookie_hash']['auth_token']
    user = User.find_by_auth_token(auth_token)
    user && user.role?(:admin)
  end
end

OsProtectRor320::Application.routes.draw do
  mount Resque::Server => '/resque', :constraints => AdminRestriction.new

  resources :sessions
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"

  resources :password_resets

  resources :sensors, :only => [:index, :edit, :update]

  get "pulse" => "dashboard#index", :as => "pulse"
  get "user_setup_required" => "dashboard#user_setup_required", :as => "user_setup_required"

  resources :incidents
  resources :incident_events, :only => [:destroy]

  resources :users

  resources :groups

  resources :notifications
  resources :notification_results, :only => [:index, :show, :destroy]

  resources :reports
  get "report_listing_events" => "reports#events_listing", :as => "report_listing_events"
  get "reports_pdf" => "reports#create_pdf", :as => "reports_pdf"

  resources :pdfs, :only => [:index, :show, :destroy]

  resources :events, :only => [:index, :show, :create, :create_pdf]
  get "home" => "events#index", :as => "home"
  post "events_pdf" => "events#create_pdf", :as => "events_pdf"

  root :to => "dashboard#index"
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  has_many :notification_results, dependent: :destroy

  serialize :notify_criteria, ActiveSupport::HashWithIndifferentAccess

  attr_accessible :user_id, :email, :run_status, :notify_criteria, :notify_criteria_as_string

  before_validation :set_notify_criteria_as_string

  validates :notify_criteria_as_string, uniqueness: {scope: :user_id, message: "you already have a Notification with the same criteria!"}
  validate :minimum_matches_ok
  validate :source_address_ok
  validate :source_port_ok
  validate :destination_address_ok
  validate :destination_port_ok

  def disabled
    self.run_status == false
  end

  def status
    self.run_status ? 'enabled' : 'disabled'
  end

  def notify_email(user)
    self.email.blank? ? user.email : self.email
  end

  class Selection
    attr_accessor :id, :name
    def initialize(attributes = {})
      attributes.each do |name, value|
        send("#{name}=", value)
      end unless attributes.nil?
    end
  end

  def self.minimum_matches_selections
    mm = []
    mm << Selection.new({id:  '0', name: 'Any'})
    mm << Selection.new({id:  '1', name: '1 or more matching events'})
    mm << Selection.new({id:  '3', name: '3 or more matching events'})
    mm << Selection.new({id:  '5', name: '5 or more matching events'})
    mm << Selection.new({id:  '7', name: '7 or more matching events'})
    mm << Selection.new({id: '10', name: '10 or more matching events'})
    mm
  end

  private

  def set_notify_criteria_as_string
    self.notify_criteria_as_string =  "user_id=#{self.user.id}," + self.notify_criteria.to_s
  end

  def minimum_matches_ok
    self.errors[:minimum_matches] << "must be a number" unless Iphdr.numeric?(self.notify_criteria[:minimum_matches])
  end

  def source_address_ok
    self.errors[:source_address] << "is invalid" unless Iphdr.is_valid?(self.notify_criteria[:source_address])
  end

  def source_port_ok
    self.errors[:source_port] << "must be a number" unless Iphdr.numeric?(self.notify_criteria[:source_port])
  end

  def destination_address_ok
    self.errors[:destination_address] << "is invalid" unless Iphdr.is_valid?(self.notify_criteria[:destination_address])
  end

  def destination_port_ok
    self.errors[:destination_port] << "must be a number" unless Iphdr.numeric?(self.notify_criteria[:destination_port])
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :ensure_user_is_setup
  before_filter :can_do_notifications

  def index
    @notifications = current_user.notifications.order("updated_at desc").page(params[:page]).per_page(APP_CONFIG[:per_page])
  end

  def show
    redirect_to notifications_url
  end

  def new
    @notification = Notification.new
    @event_search = EventSearch.new(nil)
  end

  def create
    @notification = Notification.new(params[:notification])
    adjust_attributes
    if @notification.save
      redirect_to @notification, notice: 'Notification was successfully created, and you will receive an email when matches occur.'
    else
      @event_search = EventSearch.new(params[:q])
      render action: "new"
    end
  end

  def edit
    @notification = current_user.notifications.find(params[:id])
    @event_search = EventSearch.new(@notification.notify_criteria)
  end

  def update
    @notification = current_user.notifications.find(params[:id])
    adjust_attributes
    if @notification.update_attributes(params[:notification])
      redirect_to @notification, notice: 'Notification was successfully updated.'
    else
      @event_search = EventSearch.new(params[:q])
      render action: "edit"
    end
  end

  def destroy
    @notification = current_user.notifications.find(params[:id])
    @notification.destroy
    redirect_to notifications_url
  end

  private

  def can_do_notifications
    return if APP_CONFIG[:can_do_notifications]
    flash[:error] = "Access denied: Notifications are not available."
    redirect_to root_url
  end

  def adjust_attributes
    # ignore date ranges by resetting them:
    params[:q][:relative_date_range] = ""
    params[:q][:timestamp_gte] = ""
    params[:q][:timestamp_lte] = ""
    @notification.user_id = current_user.id if @notification.user_id.blank? # preserve the original creator/owner id
    @notification.notify_criteria = params[:q]
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<div id="wrapper">
  <div id="content_wrapper">
    <div class="flashes">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :class=>"flash flash_#{name}" %>
      <% end %>
    </div>
    <div id="osprotect_content" class="with_sidebar">
      <div id="main_content_wrapper">
        <div id="main_content">
          <div id="incident">
            <%= form_for(@notification) do |f| %>
              <% if @notification.errors.any? %>
                <div id="error_explanation">
                  <h3><%= pluralize(@notification.errors.count, "error") %> prohibited this Notification from being saved:</h3>
                  <ul>
                  <% @notification.errors.full_messages.each do |msg| %>
                    <li><h3><%= msg %></h3></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>
              <fieldset class="inputs">
                <ol>
                  <li class="run_status required">
                    <label>Status</label>
                    <%= f.select(:run_status, options_for_select([["enabled", true], ["disabled", false]], selected: @notification.run_status)) %>
                  </li>
                  <li class="note">
                    <label>&nbsp;</label>
                    <em>note: when enabled this notification job will run in the background every minute</em>
                  </li>
                  <li class="email">
                    <label>Email</label>
                    <% @notification.email = @notification.notify_email(current_user) %>
                    <%= f.text_field :email %>
                  </li>
                  <li>
                    <label>&nbsp;</label>
                    <em>note: you may enter an alternate email for notifications</em>
                  </li>
                  <%#= render partial: 'criteria' %>
                  <li>
                    <label>Event Selection<br />Criteria</label>
                  </li>
                  <fieldset class="inputs" style="margin-top:-12px; margin-left:140px">
                    <ol>
                      <li class="minimum_matches">
                        <label>Minimum matches</label>
                        <%= collection_select('q', :minimum_matches, Notification.minimum_matches_selections, :id, :name, selected: @event_search.minimum_matches) %>
                      </li>
                      <li class="priority">
                        <label>Priority</label>
                        <%= collection_select('q', :sig_priority, SignatureDetail.priorities(current_user), :sig_priority, :sig_priority, include_blank: true, selected: @event_search.sig_priority) %>
                      </li>
                      <li class="signature">
                        <label>Signature</label>
                        <%= collection_select('q', :sig_id, SignatureDetail.selections(current_user), :id, :sig_name, include_blank: true, selected: @event_search.sig_id) %>
                      </li>
                      <li class="source_address">
                        <label>Source IP Address</label>
                        <%= text_field_tag 'q[source_address]', @event_search.source_address, size: "30" %>
                      </li>
                      <li class="source_port">
                        <label>Source Port</label>
                        <%= text_field_tag 'q[source_port]', @event_search.source_port, size: "30" %>
                      </li>
                      <li class="destination_address">
                        <label>Destination IP Address</label>
                        <%= text_field_tag 'q[destination_address]', @event_search.destination_address, size: "30" %>
                      </li>
                      <li class="destination_port">
                        <label>Destination Port</label>
                        <%= text_field_tag 'q[destination_port]', @event_search.destination_port, size: "30" %>
                      </li>
                      <li class="sensor">
                        <label>Detection Engine</label>
                        <%= collection_select('q', :sensor_id, Sensor.selections(current_user), :id, :hostname, include_blank: true, selected: @event_search.sensor_id) %>
                      </li>
                    </ol>
                  </fieldset>
                  <li class="buttons commit" style="margin-top:-15px">
                    <label>&nbsp;</label>
                    <%= f.submit %>
                  </li>
                </ol>
              </fieldset>
            <% end %>
          </div> <!-- incident -->
        </div> <!-- main_content -->
      </div> <!-- main_content_wrapper -->

      <div id="sidebar">
        <div class="sidebar_section panel">
          <h3 style="margin-top:-2px">&larr; <%= @notification.new_record? ? "new Notification" : "Notification: #{@notification.id}" %></h3>
          <div class="panel_contents">
              <!-- <ul>
                <li>You have <%#= number_with_delimiter current_user.notifications.count %> notifications.</li>
              </ul> -->
          </div> <!-- panel_contents -->
        </div> <!-- sidebar_section -->
      </div> <!-- sidebar -->

    </div> <!-- osprotect_content -->
  </div> <!-- content_wrapper -->
</div> <!-- wrapper -->

app/views/notifications/edit.html.erb
<% @title = 'Edit Notification' %>
<%= render 'form' %>

app/views/notifications/index.html.erb
<% @title = 'Notifications' %>
<div class="flashes">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :class=>"flash flash_#{name}" %>
  <% end %>
</div>
<div id="osprotect_content" class="without_sidebar">
  <div id="main_content_wrapper">
    <div id="main_content">
      <div class="paginated_collection">
        <%= form_tag new_notification_path, method: :get do %>
          <div class="buttons" id="add_new_notification">
            <%= submit_tag 'New Notification' %>
          </div>
        <% end %>
        <div class="pagination_information"><%= page_entries_info @notifications %></div>
        <div class="paginated_collection_contents">
          <div class="index_content">
            <div class="index_as_table">
              <table border="0" cellspacing="0" cellpadding="0" id="events" class="index_table">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Results</th>
                    <th>Event Selection Criteria</th>
                    <th>Status</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  <% unless @notifications.blank? %>
                      <% @notifications.each do |notification| %>
                          <tr class="<%= cycle('even', 'odd') %>">
                            <td><%= link_to notification.id, edit_notification_path(notification) %></td>
                            <td>
                              <% if notification.notification_results.count > 0 %>
                                  <%= link_to "#{notification.notification_results.count}", notification_results_path(id: notification) %>
                              <% else %>
                                  none
                              <% end %>
                            </td>
                            <td>
                              <%# definitely need a presenter here to handle the display of criteria %>
                              <% unless notification.notify_criteria.blank? %>
                                  <span style="font-size:0.9em">
                                    <ul>
                                      <% notification.notify_criteria.each do |key,value|
                                          next if value.blank?
                                          key = 'priority' if key == 'sig_priority'
                                          value = 'any' if key == 'minimum_matches' && value == '0'
                                          if key == 'sensor_id'
                                            key = 'sensor'
                                            value = Sensor.find(value.to_i).hostname
                                          end
                                          if key == 'sig_id'
                                            key = 'signature'
                                            value = SignatureDetail.find(value.to_i).sig_name
                                          end
                                        %>
                                        <li><em><%=key%>:</em> <strong><%=value%></strong></li>
                                      <% end %>
                                    </ul>
                                  </span>
                              <% end %>
                            </td>
                            <td><%= notification.status %></td>
                            <td><%= link_to 'delete', notification, confirm: 'Are you sure?', method: :delete %></td>
                          </tr>
                      <% end %>
                  <% else %>
                    <tr><td colspan="6"><h3>No notifications found!</h3></td></tr>
                  <% end %>
                </tbody>
              </table>
            </div> <!-- index_as_table -->
          </div> <!-- index_content -->
        </div> <!-- paginated_collection_contents -->
        <div id="index_footer">
          <%= will_paginate @notifications %>
        </div> <!-- index_footer -->
      </div> <!-- paginated_collection -->
    </div> <!-- main_content -->
  </div> <!-- main_content_wrapper -->
</div> <!-- osprotect_content -->

app/views/notifications/new.html.erb
<% @title = 'New Notification' %>
<%= render 'form' %>