config/routes.rb
class AdminRestriction
  def matches?(request)
    # user_id = request.env['rack.session'][:user_id]
    auth_token = request.env['rack.request.cookie_hash']['auth_token']
    user = User.find_by_auth_token(auth_token)
    user && user.role?(:admin)
  end
end

OsProtectRor320::Application.routes.draw do
  mount Resque::Server => '/resque', :constraints => AdminRestriction.new

  resources :sessions
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"

  resources :password_resets

  resources :sensors, :only => [:index, :edit, :update]

  get "pulse" => "dashboard#index", :as => "pulse"
  get "user_setup_required" => "dashboard#user_setup_required", :as => "user_setup_required"

  resources :incidents
  resources :incident_events, :only => [:destroy]

  resources :users

  resources :groups

  resources :notifications
  resources :notification_results, :only => [:index, :show, :destroy]

  resources :reports
  get "report_listing_events" => "reports#events_listing", :as => "report_listing_events"
  get "reports_pdf" => "reports#create_pdf", :as => "reports_pdf"

  resources :pdfs, :only => [:index, :show, :destroy]

  resources :events, :only => [:index, :show, :create, :create_pdf]
  get "home" => "events#index", :as => "home"
  post "events_pdf" => "events#create_pdf", :as => "events_pdf"

  root :to => "dashboard#index"
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  has_many :group_sensors, dependent: :destroy
  has_many :sensors, through: :group_sensors
  has_many :report_groups, dependent: :destroy
  # incidents actually belong to a user, so don't 'dependent: :destroy'
  # ... this user may be reassigned, plus admin's can see any incidents:
  has_many :incidents
  # notifications actually belong to a user, so don't 'dependent: :destroy'
  # ... this user may be reassigned, plus admin's can see any notifications:
  has_many :notifications

  attr_accessible :name, :user_ids, :user_tokens, :sensor_ids
  attr_reader :user_tokens

  validates :name, presence: true
  validates :sensor_ids, presence: {message: "at least one must be selected", unless: :group_is_admins?}
  validates :user_ids, presence: {message: "at least one must be selected"}

  after_save :change_role_to_admin_for_admins_group

  def group_is_admins?
    self.name.downcase == 'admins'
  end

  def user_tokens=(ids)
    self.user_ids = ids.split(",")
  end

  private

  def change_role_to_admin_for_admins_group
    if self.group_is_admins?
      # the default role is 'user' so let's change it to 'admin'
      Membership.transaction do
        self.memberships.each do |member|
          member.role = 'admin'
          member.save(validate: false)
        end
      end
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :ensure_user_is_setup

  load_and_authorize_resource

  def index
    @groups = Group.order("updated_at desc").page(params[:page]).per_page(APP_CONFIG[:per_page])
  end

  def show
    redirect_to groups_url
    # @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    # note: activerecord will ignore the empty values for user_ids/sensor_ids, so while 
    #       the following code isn't necessary it does make the situation clearer:
    params[:group][:user_ids].reject!(&:empty?) unless params[:group][:user_ids].blank?
    params[:group][:sensor_ids].reject!(&:empty?) unless params[:group][:sensor_ids].blank?
    @group = Group.new(params[:group])
    if @group.save
      redirect_to groups_url, notice: 'Group was successfully created.'
    else
      render action: "new"
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    # note: activerecord will ignore the empty values for user_ids/sensor_ids, so while 
    #       the following code isn't necessary it does make the situation clearer:
    params[:group][:user_ids].reject!(&:empty?) unless params[:group][:user_ids].blank?
    params[:group][:sensor_ids].reject!(&:empty?) unless params[:group][:sensor_ids].blank?
    @group = Group.find(params[:id])
    if @group.update_attributes(params[:group])
      redirect_to groups_url, notice: 'Group was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @group = Group.find(params[:id])
    if @group.group_is_admins?
      flash[:error] = "Deleting the admins group is not allowed."
      redirect_to groups_url
      return 
    end
    @group.destroy
    redirect_to groups_url
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<div id="wrapper">
  <div id="content_wrapper">
    <div class="flashes">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :class=>"flash flash_#{name}" %>
      <% end %>
    </div>
    <div id="osprotect_content" class="with_sidebar">
      <div id="main_content_wrapper">
        <div id="main_content">
          <div id="incident">
            <%= form_for(@group) do |f| %>
              <% if @group.errors.any? %>
                <div id="error_explanation">
                  <h3><%= pluralize(@group.errors.count, "error") %> prohibited this Group from being saved:</h3>
                  <ul>
                  <% @group.errors.full_messages.each do |msg| %>
                    <li><h3><%= msg %></h3></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>
              <fieldset class="inputs">
                <ol>
                  <li class="name required">
                    <label>Name</label>
                    <% if @group.name && @group.name.downcase == 'admins' %>
                      <%= @group.name %>
                    <% else %>
                      <%= f.text_field :name %>
                    <% end %>
                  </li>
                  <li class="check_boxes sensors required">
                    <label>Sensors</label>
                    <%#= collection_select(:sensor, :id, Sensor.all, :id, :hostname, {selected: @group.sensors.first}, {multiple: true, size: 5}) %>
                    <% if @group.name && @group.name.downcase == 'admins' %>
                      <strong>All</strong>
                    <% else %>
                      <%= hidden_field_tag "group[sensor_ids][]", nil %>
                      <fieldset>
                        <ol>
                          <% Sensor.all.each do |sensor| %>
                            <li>
                              <%= check_box_tag "group[sensor_ids][]", sensor.id, @group.sensor_ids.include?(sensor.id), id: dom_id(sensor) %>
                              <%#= label_tag dom_id(sensor), sensor.hostname %>
                              <%= sensor.hostname %>
                            </li>
                          <% end %>
                        </ol>
                      </fieldset>
                    <% end %>
                  </li>
                  <li class="check_boxes users required">
                    <% if @group.name && @group.name.downcase == 'admins' %>
                      <label>Users with admin privileges</label>
                    <% else %>
                      <label>Users</label>
                    <% end %>
                    <%#= collection_select(:user, :id, User.all, :id, :username, {selected: @group.users.first}, {multiple: true, size: 5}) %>
                    <%= hidden_field_tag "group[user_ids][]", nil %>
                    <fieldset>
                      <ol>
                        <% User.all.each do |user| %>
                          <% if user.username.strip.downcase == 'admin' && @group.name && @group.name.downcase == 'admins' %>
                              <li>
                                <%= check_box_tag "group[user_ids][]", user.id, @group.user_ids.include?(user.id), disabled: "disabled" %>
                                <%= user.username %>
                                &nbsp;&nbsp;&nbsp;
                                <em>note: that the default admin can not be removed from this group.</em>
                                <%= hidden_field_tag "group[user_ids][]", user.id %>
                              </li>
                          <% else %>
                              <li>
                                <%= check_box_tag "group[user_ids][]", user.id, @group.user_ids.include?(user.id), id: dom_id(user) %>
                                <%#= label_tag dom_id(user), user.username %>
                                <%= user.username %>
                              </li>
                          <% end %>
                        <% end %>
                      </ol>
                    </fieldset>
                  </li>
                  <li class="buttons commit">
                    <label>&nbsp;</label>
                    <%= f.submit %>
                  </li>
                </ol>
              </fieldset>
            <% end %>
          </div> <!-- incident -->
        </div> <!-- main_content -->
      </div> <!-- main_content_wrapper -->

      <div id="sidebar">
        <div class="sidebar_section panel">
          <h3 style="margin-top:-2px">&larr; <%= @group.new_record? ? "new Group" : "Group: #{@group.name}" %></h3>
          <div class="panel_contents">
              <ul>
                <li>Users count: <%= number_with_delimiter @group.users.count %></li>
                <li>Sensors count: 
                <% if @group.name && @group.name.downcase == 'admins' %>
                    All
                <% else %>
                    <%= number_with_delimiter @group.group_sensors.count %>
                <% end %>
                </li>
              </ul>
          </div> <!-- panel_contents -->
        </div> <!-- sidebar_section -->
      </div> <!-- sidebar -->

    </div> <!-- osprotect_content -->
  </div> <!-- content_wrapper -->
</div> <!-- wrapper -->

app/views/groups/edit.html.erb
<% @title = 'Edit Group' %>
<%= render 'form' %>

app/views/groups/index.html.erb
<% @title = 'Groups' %>
<div class="flashes">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :class=>"flash flash_#{name}" %>
  <% end %>
</div>
<div id="osprotect_content" class="without_sidebar">
  <div id="main_content_wrapper">
    <div id="main_content">
      <div class="paginated_collection">
        <%= form_tag new_group_path, method: :get do %>
          <div class="buttons" id="add_new_group">
            <%= submit_tag 'New Group' %>
          </div>
        <% end %>
        <div class="pagination_information"><%= page_entries_info @groups %></div>
        <div class="paginated_collection_contents">
          <div class="index_content">
            <div class="index_as_table">
              <table border="0" cellspacing="0" cellpadding="0" id="events" class="index_table">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Users</th>
                    <th>Sensors</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  <% if @groups %>
                      <% @groups.each do |group| %>
                          <tr class="<%= cycle('even', 'odd') %>">
                            <td><%= link_to group.name, edit_group_path(group) %></td>
                            <td><%= group.users.map {|u| u.username}.join(', ') %></td>
                            <td>
                              <% if group.name.downcase == 'admins' %>
                                <strong>All</strong>
                              <% else %>
                                <%#= group.group_sensors.map {|gs| gs.sensor_name}.join(', ') %>
                                <%#= group.group_sensors.map {|gs| gs.sensor_id}.join(', ') %>
                                <%= group.group_sensors.map {|gs| gs.sensor.hostname}.join(', ') %>
                              <% end %>
                            </td>
                            <td>
                              <% if group.group_is_admins? %>
                                &nbsp;
                              <% else %>
                                <%= link_to 'delete', group, confirm: 'Are you sure?', method: :delete %>
                              <% end %>
                            </td>
                          </tr>
                      <% end %>
                  <% else %>
                    <tr><td colspan="6"><h3>No groups found!</h3></td></tr>
                  <% end %>
                </tbody>
              </table>
            </div> <!-- index_as_table -->
          </div> <!-- index_content -->
        </div> <!-- paginated_collection_contents -->
        <div id="index_footer">
          <%= will_paginate @groups %>
        </div> <!-- index_footer -->
      </div> <!-- paginated_collection -->
    </div> <!-- main_content -->
  </div> <!-- main_content_wrapper -->
</div> <!-- osprotect_content -->

app/views/groups/new.html.erb
<% @title = 'New Group' %>
<%= render 'form' %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @group.user %>
</p>

<p>
  <b>Group sensor:</b>
  <%= @group.group_sensor %>
</p>

<p>
  <b>Name:</b>
  <%= @group.name %>
</p>


<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>