config/routes.rb
class AdminRestriction
  def matches?(request)
    # user_id = request.env['rack.session'][:user_id]
    auth_token = request.env['rack.request.cookie_hash']['auth_token']
    user = User.find_by_auth_token(auth_token)
    user && user.role?(:admin)
  end
end

OsProtectRor320::Application.routes.draw do
  mount Resque::Server => '/resque', :constraints => AdminRestriction.new

  resources :sessions
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"

  resources :password_resets

  resources :sensors, :only => [:index, :edit, :update]

  get "pulse" => "dashboard#index", :as => "pulse"
  get "user_setup_required" => "dashboard#user_setup_required", :as => "user_setup_required"

  resources :incidents
  resources :incident_events, :only => [:destroy]

  resources :users

  resources :groups

  resources :notifications
  resources :notification_results, :only => [:index, :show, :destroy]

  resources :reports
  get "report_listing_events" => "reports#events_listing", :as => "report_listing_events"
  get "reports_pdf" => "reports#create_pdf", :as => "reports_pdf"

  resources :pdfs, :only => [:index, :show, :destroy]

  resources :events, :only => [:index, :show, :create, :create_pdf]
  get "home" => "events#index", :as => "home"
  post "events_pdf" => "events#create_pdf", :as => "events_pdf"

  root :to => "dashboard#index"
end

app/models/notification_result.rb
class NotificationResult < ActiveRecord::Base
  belongs_to :notification

  serialize :notify_criteria_for_this_result, ActiveSupport::HashWithIndifferentAccess

  serialize :result_ids, Array
end

app/controllers/notification_results_controller.rb
class NotificationResultsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :ensure_user_is_setup

  def index
    @notification = current_user.notifications.find(params[:id])
    @notification_results = @notification.notification_results.order("updated_at desc").page(params[:page]).per_page(APP_CONFIG[:per_page])
  end

  def show
    # show matching events for this notification result:
    @notification_result = current_user.notification_results.find(params[:id])
    @notification = Notification.find(@notification_result.notification.id)
    # @events = @notification_result.result_ids.map { |id| Event.find(id) }
    sids = @notification_result.result_ids.map{|r| r[0]}
    cids = @notification_result.result_ids.map{|r| r[1]}
    @events = Event.where(sid: sids, cid: cids).page(params[:page]).per_page(APP_CONFIG[:per_page])
  end

  def new
    redirect_to notification_results_url
  end

  def create
    redirect_to notification_results_url
  end

  def edit
    redirect_to notification_results_url
  end

  def update
    redirect_to notification_results_url
  end

  def destroy
    @notification_result = current_user.notification_results.find(params[:id])
    notification_id = @notification_result.notification.id
    @notification_result.destroy
    redirect_to notification_results_url(id: notification_id)
  end
end

app/views/notification_results/_incident.html.erb
<% if incident.blank? %>
  <div class="incident">
    No events were selected!
  </div>
<% else %>
  <div id="<%=dom_id(incident)%>" class="incident">
    <strong><%= incident.events_added_count %></strong> <small><em>events added to incident</em></small> 
    <strong><%= link_to incident.incident_name, edit_incident_path(id: incident.id) %></strong>
    <% if incident.events_rejected_count > 0 %>
        &nbsp;&nbsp;<small><em>(<%=incident.events_rejected_count%> rejected duplicates)</em></small> 
    <% end %>
    <!-- <small><em>created on <%#= incident.created_at.strftime('%b %d, %Y at %I:%M %p') unless incident.created_at.blank? %></em></small> -->
    <%#= link_to "Remove", incident, :method => :delete, :remote => true %>
    <%#= simple_format incident.incident_description %>
  </div>
<% end %>

app/views/notification_results/index.html.erb
<% @title = 'Notification Results' %>
<div class="flashes">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :class=>"flash flash_#{name}" %>
  <% end %>
</div>
<div id="osprotect_content" class="without_sidebar">
  <div id="main_content_wrapper">
    <div id="main_content">
      <div class="paginated_collection">
        <h3><%= link_to "Notification #{@notification.id}", edit_notification_path(id: @notification.id) %> results:</h3>
        <div class="pagination_information"><%= page_entries_info @notification_results %></div>
        <div class="paginated_collection_contents">
          <div class="index_content">
            <div class="index_as_table">
              <table border="0" cellspacing="0" cellpadding="0" id="events" class="index_table">
                <thead>
                  <tr>
                    <th></th>
                    <th>Events Matched</th>
                    <th>From</th>
                    <th>To</th>
                    <th>Created</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  <% unless @notification_results.blank? %>
                      <% @notification_results.each do |nr| %>
                          <tr class="<%= cycle('even', 'odd') %>">
                            <td><%= link_to "view", notification_result_path(id: nr.id), style: "text-decoration:none" %></td>
                            <td><%= nr.total_matches %></td>
                            <td><%= nr.events_timestamped_from %></td>
                            <td><%= nr.events_timestamped_to %></td>
                            <td><%= nr.created_at %></td>
                            <td><%= link_to 'delete', nr, confirm: 'Are you sure?', method: :delete %></td>
                          </tr>
                      <% end %>
                  <% else %>
                    <tr><td colspan="6"><h3>No notification results found!</h3></td></tr>
                  <% end %>
                </tbody>
              </table>
            </div> <!-- index_as_table -->
          </div> <!-- index_content -->
        </div> <!-- paginated_collection_contents -->
        <div id="index_footer">
          <%= will_paginate @notification_results %>
        </div> <!-- index_footer -->
      </div> <!-- paginated_collection -->
    </div> <!-- main_content -->
  </div> <!-- main_content_wrapper -->
</div> <!-- osprotect_content -->

app/views/notification_results/show.html.erb
<% @title = 'Notification Results' %>
<% presenting @events, "EventPagePresenter" do |presenter| %>
  <div class="flashes">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :class=>"flash flash_#{name}" %>
    <% end %>
    <div id="incident" class="flash flash_notice" style="display:none">
      <%= render partial: 'incident', locals: {incident: @incident} %>
    </div>
  </div>
  <div id="osprotect_content" class="with_sidebar">
    <div id="main_content_wrapper">
      <div id="main_content">
        <% unless @events.blank? %>
          <div class="paginated_collection">
            <%= form_tag events_path, method: :post, :remote => :true, class: "event_select_form" do %>
              <% if @events.size > 0 %>
                  <div class="buttons" id="add-selected-events">
                    <%= submit_tag 'Add selected events to', id: 'submit-selected-events' %>
                    <%= select_tag(:incident_id, options_for_select(Incident.all.collect {|i| [ "##{i.id} - #{truncate(i.incident_name)}", i.id ] }), {prompt: "a new Incident or select from this list"}) %>
                  </div>
                  <div id="adding-events-spinner" style="display:none">
                    <%= image_tag('loading-bars.gif') %>
                  </div>
              <% end %>
              <div class="pagination_information">&nbsp;<%= page_entries_info @events %></div>
              <div class="paginated_collection_contents">
                <div class="index_content">
                  <div class="index_as_table">
                    <% if @events.size > 0 %>
                        <table border="0" cellspacing="0" cellpadding="0" id="events" class="index_table">
                          <thead>
                            <tr>
                              <th class="sortable small">
                                <%= image_tag('check.png', id: 'events-check', title: 'click to toggle checkboxes')%>
                              </th>
                              <th class="sortable">Priority</th>
                              <th class="sortable">Signature</th>
                              <th class="sortable">Source</th>
                              <th class="sortable">Destination</th>
                              <th class="sortable">Sensor</th>
                              <th class="sortable">Timestamp</th>
                            </tr>
                          </thead>
                          <tbody>
                            <% @events.each_with_index do |event, x| %>
                                <tr class="<%= cycle('even', 'odd') %>">
                                  <td><%= check_box_tag "event[#{x}]", event.key, false, :id => "check_box_#{event.key_with_underscore}", :class => 'select-events' %></td>
                                  <td><%=event.priority%></td>
                                  <td><%= link_to event.signature, event_path(event.key) %></td>
                                  <td><%=event.source_ip_port%></td>
                                  <td><%=event.destination_ip_port%></td>
                                  <td><%=event.sensor_name%></td>
                                  <td><%=event.timestamp%></td>
                                </tr>
                            <% end %>
                          </tbody>
                        </table>
                    <% else %>
                        <br /><h2>No events found!</h2>
                    <% end %>
                  </div> <!-- index_as_table -->
                </div> <!-- index_content -->
              </div> <!-- paginated_collection_contents -->
            <% end %> <!-- form_tag events_path -->

            <div id="index_footer">
              <div style="float:left">
                <%#= button_to 'create PDF', events_pdf_url(q: params[:q], format: :pdf), method: "post" %>
                <%# the following opens a new tab in the browser: %>
                <%#= button_to 'create PDF', events_pdf_url(q: params[:q], format: :pdf), method: "post", form: {"target" => "_blank"} %>
              </div>
              <%= will_paginate @events %>
            </div>
          </div> <!-- paginated_collection -->
        <% else %>
          <br /><h2>No events found!</h2>
        <% end %>
      </div> <!-- main_content -->
    </div> <!-- main_content_wrapper -->

    <div id="sidebar">
      <div class="spacer57"></div>
      <div class="sidebar_section panel">
        <h3>&larr; Results for notification: <%= "#{@notification.id}" %></h3>
        <div class="panel_contents">
            <ul style="list-style-type:none">
              <li>- events matched: <strong><%= number_with_delimiter @notification_result.total_matches %></strong></li>
              <li>- email sent: <strong><%= @notification_result.email_sent ? "yes" : "no" %></strong></li>
              <li>- results are from:</li>
              <li style="padding-left:20px"><strong><%= @notification_result.events_timestamped_from %></strong></li>
              <li style="padding-left:50px">to:</li>
              <li style="padding-left:20px"><strong><%= @notification_result.events_timestamped_to %></strong></li>
              <li>- match criteria:</strong></li>
              <li style="padding-left:20px">
                <% unless @notification_result.notify_criteria_for_this_result.blank? %>
                    <span style="font-size:0.9em">
                      <ul>
                        <% @notification_result.notify_criteria_for_this_result.each do |key,value|
                            next if value.blank?
                            key = 'priority' if key == 'sig_priority'
                            value = 'any' if key == 'minimum_matches' && value == '0'
                            if key == 'sensor_id'
                              key = 'sensor'
                              value = Sensor.find(value.to_i).hostname
                            end
                            if key == 'sig_id'
                              key = 'signature'
                              value = SignatureDetail.find(value.to_i).sig_name
                            end
                          %>
                          <li><em><%=key%>:</em> <strong><%=value%></strong></li>
                        <% end %>
                      </ul>
                    </span>
                <% end %>
              </li>
              <li>- recorded: <%= @notification_result.created_at %></li>
            </ul>
        </div> <!-- panel_contents -->
      </div> <!-- sidebar_section -->
    </div> <!-- sidebar -->

  </div> <!-- osprotect_content -->
<% end %>