config/routes.rb
class AdminRestriction
  def matches?(request)
    # user_id = request.env['rack.session'][:user_id]
    auth_token = request.env['rack.request.cookie_hash']['auth_token']
    user = User.find_by_auth_token(auth_token)
    user && user.role?(:admin)
  end
end

OsProtectRor320::Application.routes.draw do
  mount Resque::Server => '/resque', :constraints => AdminRestriction.new

  resources :sessions
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"

  resources :password_resets

  resources :sensors, :only => [:index, :edit, :update]

  get "pulse" => "dashboard#index", :as => "pulse"
  get "user_setup_required" => "dashboard#user_setup_required", :as => "user_setup_required"

  resources :incidents
  resources :incident_events, :only => [:destroy]

  resources :users

  resources :groups

  resources :notifications
  resources :notification_results, :only => [:index, :show, :destroy]

  resources :reports
  get "report_listing_events" => "reports#events_listing", :as => "report_listing_events"
  get "reports_pdf" => "reports#create_pdf", :as => "reports_pdf"

  resources :pdfs, :only => [:index, :show, :destroy]

  resources :events, :only => [:index, :show, :create, :create_pdf]
  get "home" => "events#index", :as => "home"
  post "events_pdf" => "events#create_pdf", :as => "events_pdf"

  root :to => "dashboard#index"
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user
  has_many :report_groups, dependent: :destroy
  has_many :groups, through: :report_groups
  has_many :pdfs, dependent: :destroy

  serialize :report_criteria, ActiveSupport::HashWithIndifferentAccess

  attr_accessor :accessible_by

  attr_accessible :accessible_by, :group_ids, :user_id, :report_type, :for_all_users, :name, :include_summary, 
                  :auto_run_at, :run_status, :report_criteria, :report_criteria_as_string

  before_validation :set_report_criteria_as_string

  validates :report_criteria_as_string, uniqueness: {scope: :user_id, message: "a similar Report already exists"}
  validates :name, presence: true
  validate :group_ids_ok
  validate :source_address_ok
  validate :source_port_ok
  validate :destination_address_ok
  validate :destination_port_ok
  validate :timestamp_gte_ok
  validate :timestamp_lte_ok
  validate :date_range_presence
  validate :date_range_is_relative_or_fixed_but_not_both
  validate :date_range_is_fixed_so_both_dates_required
  validate :date_range_is_fixed_so_range_must_be_proper

  class Selection
    attr_accessor :id, :name
    def initialize(attributes = {})
      attributes.each do |name, value|
        send("#{name}=", value)
      end unless attributes.nil?
    end
  end

  def self.relative_date_ranges
    rdr = []
    rdr << Selection.new({id: 'today',      name: 'Today'})
    rdr << Selection.new({id: 'last_24',    name: 'Last 24 Hours'})
    rdr << Selection.new({id: 'week',       name: 'This Week'})
    rdr << Selection.new({id: 'last_week',  name: 'Last Week'})
    rdr << Selection.new({id: 'month',      name: 'This Month'})
    rdr << Selection.new({id: 'past_year',  name: 'Past Year'})
    rdr << Selection.new({id: 'year',       name: 'Year'})
    rdr
  end

  def self.auto_run_selections
    ar = []
    ar << Selection.new({id: 'd', name: 'Daily'})   if APP_CONFIG[:can_daily_report]
    ar << Selection.new({id: 'w', name: 'Weekly'})  if APP_CONFIG[:can_weekly_report]
    ar << Selection.new({id: 'w', name: 'Monthly'}) if APP_CONFIG[:can_monthly_report]
    ar
  end

  def self.access_allowed_selections(user)
    ar = []
    ar << Selection.new({id: 'm', name: 'only me'})
    ar << Selection.new({id: 'a', name: 'any group or user'}) if user && user.role?(:admin)
    ar << Selection.new({id: 'g', name: 'for group(s) selected below'})
    ar
  end

  def enabled
    self.run_status == true
  end

  def disabled
    self.run_status == false
  end

  def auto_run_at_to_s
    return "" if self.auto_run_at.blank?
    return Report.auto_run_selections.select {|p| p.id == self.auto_run_at}.first.name
  end

  def is_auto_run?
    return false if self.auto_run_at.blank?
    return Report.auto_run_selections.select {|p| p.id == self.auto_run_at}.first.id == self.auto_run_at
  end

  def status
    self.run_status ? 'enabled' : 'disabled'
  end

  def group_ids_as_array
    gids = []
    self.groups.map {|g| gids << g.id}
    gids
  end

  def users_pdf_count_for_this_report(user_id)
    Pdf.includes(:report, :user).where(user_id: user_id, report_id: self.id).count
  end

  private

  def set_report_criteria_as_string
    self.report_criteria_as_string =  "report=#{self.report_type}," +
                                      "include_summary=#{self.include_summary}," +
                                      "auto_run_at=#{self.auto_run_at}," +
                                      self.report_criteria.to_s
  end

  def group_ids_ok
    self.errors[:group_ids] << "missing Group selection(s)" if self.accessible_by == 'g' && self.groups.blank?
    self.errors[:group_ids] << "Group(s) selected but 'To' is 'only me'" if self.accessible_by == 'm' && self.groups.any?
    self.errors[:group_ids] << "Group(s) selected but 'To' is 'any group or user'" if self.accessible_by == 'a' && self.groups.any?
  end

  def source_address_ok
    self.errors[:source_address] << "is invalid" unless Iphdr.is_valid?(self.report_criteria[:source_address])
  end

  def source_port_ok
    self.errors[:source_port] << "must be a number" unless Iphdr.numeric?(self.report_criteria[:source_port])
  end

  def destination_address_ok
    self.errors[:destination_address] << "is invalid" unless Iphdr.is_valid?(self.report_criteria[:destination_address])
  end

  def destination_port_ok
    self.errors[:destination_port] << "must be a number" unless Iphdr.numeric?(self.report_criteria[:destination_port])
  end

  def timestamp_gte_ok
    return unless self.auto_run_at.blank?
    self.errors[:timestamp_gte] << "is invalid" unless valid_date? self.report_criteria[:timestamp_gte]
  end

  def timestamp_lte_ok
    return unless self.auto_run_at.blank?
    self.errors[:timestamp_lte] << "is invalid" unless valid_date? self.report_criteria[:timestamp_lte]
  end

  def date_range_presence
    return unless self.auto_run_at.blank?
    self.errors[:date_range] << "a relative or fixed date range is required" if self.report_criteria[:relative_date_range].blank? && self.report_criteria[:timestamp_gte].blank? && self.report_criteria[:timestamp_lte].blank?
  end

  def date_range_is_relative_or_fixed_but_not_both
    return unless self.auto_run_at.blank?
    self.errors[:date_range] << "can not be both relative and fixed, please enter only a relative or fixed date range" if self.report_criteria[:relative_date_range].present? && (self.report_criteria[:timestamp_gte].present? || self.report_criteria[:timestamp_lte].present?)
  end

  def date_range_is_fixed_so_both_dates_required
    return unless self.auto_run_at.blank?
    if (self.report_criteria[:timestamp_lte].present? && self.report_criteria[:timestamp_gte].blank?) ||
       (self.report_criteria[:timestamp_gte].present? && self.report_criteria[:timestamp_lte].blank?)
      self.errors[:fixed_date_range] << "both dates are required when either is entered"
    end
  end

  def date_range_is_fixed_so_range_must_be_proper
    return unless self.auto_run_at.blank?
    return if self.report_criteria[:timestamp_lte].blank? && self.report_criteria[:timestamp_gte].blank?
    begin
      self.errors[:fixed_date_range] << "begin and end dates must specify a proper range" if self.report_criteria[:timestamp_lte].to_date < self.report_criteria[:timestamp_gte].to_date
    rescue Exception => e
      return # invalid dates already handled by another validation
    end
  end

  def valid_date?(adate)
    adate.to_date
    true
  rescue Exception => e
    false
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :memberships, dependent: :destroy
  has_many :groups, through: :memberships
  has_many :incidents
  has_many :notifications, dependent: :destroy
  has_many :notification_results, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :pdfs, dependent: :destroy

  has_secure_password

  attr_accessible :username, :email, :password, :password_confirmation

  validates :email, presence: true, 
            uniqueness: {case_sensitive: false},
            length: {minimum: 3},
            format: {with: /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}
  validates :username, presence: true, 
            uniqueness: {case_sensitive: false},
            length: {minimum: 3}
  validates :password, presence: true, length: {minimum: 6}, on: :create
  validates :password, presence: true, length: {minimum: 6}, on: :update, :if => :password_digest_changed?

  before_create { generate_token(:auth_token) }

  ROLES = %w[admin user]

  def sensors
    sensors_for_user = []
    self.groups.each {|g| g.sensors.map {|s| sensors_for_user << s.id}}
    sensors_for_user
  end

  def has_sensors?
    self.sensors.count > 0
  end

  def roles
    self.memberships.map { |m| m.role.downcase }
  end

  def role?(has_role)
    roles.include? has_role.to_s.downcase
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    begin
      # note: don't pass complex objects like ActiveRecord models, just pass an id as a reference
      #       to the object(s) because the enqueue done by resque converts params to json:
      UserBackgroundMailer.password_reset(self.id).deliver
    rescue Exception => e
      puts "\nUserBackgroundMailer failed!\n Exception: #{e.message}\n Attempting foreground mailer...\n"
      UserMailer.password_reset(self.id).deliver
    end
  end
end

app/controllers/reports_controller.rb
# note: we are doing explicit require's and include's so it is clear as to what is going on, and
#       just in case some brave soul will try to run this app in thread safe mode
require "osprotect/restrict_events_based_on_users_access"
require "osprotect/date_ranges"
require "osprotect/pulse_top_tens"

class ReportsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :ensure_user_is_setup
  before_filter :can_do_reports

  include Osprotect::RestrictEventsBasedOnUsersAccess
  include Osprotect::DateRanges
  include Osprotect::PulseTopTens

  respond_to :html
  respond_to :pdf, only: [:create_pdf]

  def index
    # list reports for current_user, or current_user.groups, or admin created for all users:
    if current_user.role?(:admin)
      @reports = Report
    else
      # note if 'user_id = current_user.id' then this user is the owner of this report or 
      # the user set this report with 'Access Allowed' 'To' 'only me' (but they are still the owner)
      @reports = Report.where('for_all_users = ? OR user_id = ?', true, current_user.id)
      @reports = Report.includes(:groups).where('groups.id IN (?)', current_user.groups) if @reports.blank?
    end
    @reports = @reports.order("reports.updated_at desc").page(params[:page]).per_page(APP_CONFIG[:per_page])
  end

  def show
    redirect_to reports_url
  end

  def new
    @report = Report.new
    @report.report_type = 2 if params[:commit] == 'New Incidents Report'
    @event_search = @report.report_type == 2 ? IncidentEventSearch.new(nil) : EventSearch.new(nil)
  end

  def create
    adjust_params
    @report = Report.new(params[:report])
    adjust_report_attributes
    if @report.save
      redirect_to @report, notice: 'Report was successfully created.'
    else
      @event_search = @report.report_type == 2 ? IncidentEventSearch.new(params[:q]) : EventSearch.new(params[:q])
      render action: "new"
    end
  end

  def edit
    @report = current_user.reports.find(params[:id])
    @event_search = @report.report_type == 2 ? IncidentEventSearch.new(@report.report_criteria) : EventSearch.new(@report.report_criteria)
  end

  def update
    adjust_params
    @report = current_user.reports.find(params[:id])
    adjust_report_attributes
    if @report.update_attributes(params[:report])
      redirect_to @report, notice: 'Report was successfully updated.'
    else
      @event_search = @report.report_type == 2 ? IncidentEventSearch.new(params[:q]) : EventSearch.new(params[:q])
      render action: "edit"
    end
  end

  def destroy
    @report = current_user.reports.find(params[:id])
    @report.pdfs.each do |pdf|
      file = pdf.path_to_file + '/' + pdf.file_name
      begin
        FileUtils.rm(file) if File.exist?(file)
      rescue Errno::ENOENT => e
        # ignore file-not-found, let everything else pass
      end
    end
    @report.destroy
    redirect_to reports_url
  end

  # HTML version of report
  def events_listing
    if current_user.role?(:admin)
      @report = Report.find(params[:id])
    else
      @report = Report.where('(for_all_users = ? OR user_id = ?) AND id = ?', true, current_user.id, params[:id]).first
      @report = Report.includes(:groups).where('groups.id IN (?)', current_user.groups).first if @reports.blank?
    end
    if @report.blank?
      redirect_to reports_url, notice: "Access denied."
      return
    end
    get_events_based_on_groups_for_user(current_user.id) # sets @events
    filter_events_based_on(params[:q]) # sets @event_search
    @events = @events.page(params[:page]).per_page(APP_CONFIG[:per_page])
    set_pulse_for_partial
  end

  # PDF version of report
  def create_pdf
    respond_with do |format|
      format.html { redirect_to reports_url }
      format.pdf do
        # only allow reports for the current_user or reports that an admin created for all users:
        if current_user.role?(:admin)
          report = Report.find(params[:id])
        else
          report = Report.where('(for_all_users = ? OR user_id = ?) AND id = ?', true, current_user.id, params[:id]).first
          report = Report.includes(:groups).where('groups.id IN (?)', current_user.groups).first if @reports.blank?
        end
        if report.blank?
          redirect_to reports_url, notice: "Access denied."
          return
        end
        queued = false
        pdf = Pdf.new
        pdf.user_id = current_user.id
        pdf.report_id = report.id
        pdf.pdf_type = 1
        pdf.creation_criteria = report.report_criteria
        pdf.save!
        begin
          if Resque.info[:workers] > 0
            # note: if Redis is running then Resque can enqueue, but results in a bunch of jobs waiting for workers, 
            #       so we ensure that at least one worker has been started.
            Resque.enqueue(PdfWorker, current_user.id, pdf.id)
            queued = true
          end
        rescue Exception => e
          queued = false
        end
        if queued
          # redirect_to events_url(q: report.report_criteria), notice: "Your PDF document is being prepared, and in a few moments it will be available for download on the PDFs page."
          redirect_to reports_url, notice: "Your PDF document is being prepared, and in a few moments it will be available for download on the PDFs page."
        else
          pdf.destroy
          redirect_to reports_url, notice: "Background processing is offline, so PDF creation is not possible at this time."
        end
      end
    end
  end

  private

  def can_do_reports
    return if APP_CONFIG[:can_do_reports]
    flash[:error] = "Access denied: Reports are not available."
    redirect_to root_url
  end

  def adjust_params
    if ['a', 'm'].include?(params[:report][:accessible_by])
      params[:report][:group_ids] = []
    end
    auto_run_types = Report.auto_run_selections.collect {|p| p.id}
    if auto_run_types.include?(params[:report][:auto_run_at])
      # ignore date ranges by resetting them:
      params[:q][:relative_date_range] = ""
      params[:q][:timestamp_gte] = ""
      params[:q][:timestamp_lte] = ""
    end
  end

  def adjust_report_attributes
    # @report.report_type = 1 # default is 1=EventsReport
    @report.user_id = current_user.id if @report.user_id.blank? # i.e. don't lose original creator/owner id
    @report.for_all_users = false # only admins can set this to true
    @report.for_all_users = true if params[:report][:accessible_by] == 'a' && current_user.role?(:admin)
    @report.report_criteria = params[:q]
  end

  def set_pulse_for_partial
    take_pulse(current_user, @report.report_criteria[:relative_date_range])
  end
end

app/views/reports/edit.html.erb
<% if params[:commit] == 'create Incidents Report' || @report.report_type == 2 %>
  <% @title = 'Edit Incident Report' %>
  <%= render 'incidents_form' %>
<% else %>
  <% @title = 'Edit Event Report' %>
  <%= render 'events_form' %>
<% end %>

app/views/reports/events_listing.html.erb
<% @title = 'Report Event listings' %>
<div class="flashes">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :class=>"flash flash_#{name}" %>
  <% end %>
</div>
<div id="osprotect_content" class="with_sidebar">
  <div id="main_content_wrapper">
    <div id="main_content">
        <div class="paginated_collection">
            <h3>Report: <%= @report.name %></h3>
            <div class="pagination_information"><%= page_entries_info @events %></div>
            <div class="paginated_collection_contents">
              <div class="index_content">
                <div class="index_as_table">
                  <% if @events.blank? %>
                      <% no_events = true %>
                      <br /><h6>No events found!</h6>
                      <br />
                  <% else %>
                      <% no_events = false %>
                      <table border="0" cellspacing="0" cellpadding="0" id="events" class="index_table">
                        <thead>
                          <tr>
                            <th class="sortable">Priority</th>
                            <th class="sortable">Signature</th>
                            <th class="sortable">Source</th>
                            <th class="sortable">Destination</th>
                            <th class="sortable">Sensor</th>
                            <th class="sortable">Timestamp</th>
                          </tr>
                        </thead>
                        <tbody>
                          <% @events.each do |event| %>
                              <tr class="<%= cycle('even', 'odd') %>">
                                <td><%=event.priority%></td>
                                <td><%= link_to event.signature, event_path(event.key) %></td>
                                <td><%=event.source_ip_port%></td>
                                <td><%=event.destination_ip_port%></td>
                                <td><%=event.sensor_name%></td>
                                <td><%=event.timestamp%></td>
                              </tr>
                          <% end %>
                        </tbody>
                      </table>
                  <% end %>
                </div> <!-- index_as_table -->
              </div> <!-- index_content -->
            </div> <!-- paginated_collection_contents -->

          <div id="index_footer">
            <%= will_paginate @events %>
          </div>
        </div> <!-- paginated_collection -->
    </div> <!-- main_content -->
  </div> <!-- main_content_wrapper -->

  <div id="sidebar">
    <div class="sidebar_section panel" id="filters_sidebar_section">
      <h3 style="margin-top:40px">&larr; Report Criteria:</h3>
      <div class="panel_contents events_listing">
        <%= form_tag reports_path, method: 'get', class: "filter_form" do %>
          <div class="error_messages">
            <ul class="errors">
              <% for message in @event_search.errors.full_messages %>
                  <li class="status error"><%= message %></li>
              <% end %>
            </ul>
          </div>
          <div class="filter_form_field filter_select">
            <%= label_tag "Priority" %>
            <%= collection_select('q', :sig_priority, SignatureDetail.priorities(current_user), :sig_priority, :sig_priority, include_blank: true, selected: @event_search.sig_priority, disabled: 'disabled') %>
          </div>
          <div class="filter_form_field filter_select">
            <%= label_tag "Signature" %>
            <%= collection_select('q', :sig_id, SignatureDetail.selections(current_user), :id, :sig_name, include_blank: true, selected: @event_search.sig_id) %>
          </div>
          <div class="filter_form_field filter_string">
            <%= label_tag "source address" %>
            <%= text_field_tag 'q[source_address]', @event_search.source_address, size: "30" %>
          </div>
          <div class="filter_form_field filter_string">
            <%= label_tag "source port" %>
            <%= text_field_tag 'q[source_port]', @event_search.source_port, size: "30" %>
          </div>
          <div class="filter_form_field filter_string">
            <%= label_tag "destination address" %>
            <%= text_field_tag 'q[destination_address]', @event_search.destination_address, size: "30" %>
          </div>
          <div class="filter_form_field filter_string">
            <%= label_tag "destination port" %>
            <%= text_field_tag 'q[destination_port]', @event_search.destination_port, size: "30" %>
          </div>
          <div class="filter_form_field filter_select">
            <%= label_tag "Sensor" %>
            <%= collection_select('q', :sensor_id, Sensor.selections(current_user), :id, :hostname, include_blank: true, selected: @event_search.sensor_id) %>
          </div>
          <div class="filter_form_field filter_date_range">
            <%= label_tag "Date Range" %>
            <%= collection_select('q', :relative_date_range, Report.relative_date_ranges, :id, :name, include_blank: true, selected: @event_search.relative_date_range) %>
          </div>
          <div class="filter_form_field filter_date_range">
            <%= label_tag "Custom Date Range" %>
            <%= text_field_tag 'q[timestamp_gte]', @event_search.timestamp_gte, size: "12", maxlength: "10" %>
            <span class="seperator">-</span>
            <%= text_field_tag 'q[timestamp_lte]', @event_search.timestamp_lte, size: "12", maxlength: "10" %>
          </div>
        <% end %>
      </div> <!-- panel_contents -->
    </div> <!-- sidebar_section -->
  </div> <!-- sidebar -->

  <div class="clear"></div>
  <div class="spacer15">&nbsp;</div>
  <div class="dashboard_section panel">
    <div class="panel_contents">
      <h3 style="clear: both; text-align:center">
        Pulse for 
        <% if @report.report_criteria[:relative_date_range].blank? %>
            Date Range:&nbsp;&nbsp;
        <% else %>
            <%= @report.report_criteria[:relative_date_range].to_s.titleize %>:&nbsp;&nbsp;
        <% end %>
        <%= @start_time.utc.strftime("%a %b %d, %Y %I:%M:%S %P %Z") %>
        &nbsp;&nbsp;-&nbsp;&nbsp;
        <%= @end_time.utc.strftime("%a %b %d, %Y %I:%M:%S %P %Z") %>
      </h3>
      <%= render partial: 'shared/pulse' %>
    </div> <!-- panel_contents -->
  </div> <!-- dashboard_section -->
</div> <!-- osprotect_content -->

app/views/reports/index.html.erb
<% @title = 'Reports' %>
<div class="flashes">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :class=>"flash flash_#{name}" %>
  <% end %>
</div>
<div id="osprotect_content" class="without_sidebar">
  <div id="main_content_wrapper">
    <div id="main_content">
      <div class="paginated_collection">
        <%= form_tag new_report_path, method: :get do %>
          <div class="buttons" id="add_new_report">
            <%= submit_tag 'New Events Report' %>
            <%= submit_tag 'New Incidents Report' %>
          </div>
        <% end %>
        <div class="pagination_information"><%= page_entries_info @reports %></div>
        <div class="paginated_collection_contents">
          <div class="index_content">
            <div class="index_as_table">
              <table border="0" cellspacing="0" cellpadding="0" id="events" class="index_table">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>PDFs Created</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  <% unless @reports.blank? %>
                      <% @reports.each do |report| %>
                          <tr class="<%= cycle('even', 'odd') %>">
                            <td>
                              <% if current_user.id == report.user_id %>
                                  <%= link_to report.name, edit_report_path(report) %>
                              <% else %>
                                  <%= report.name %>
                              <% end %>
                            </td>
                            <td>
                              <% if report.is_auto_run? %>
                                  <em>auto-run reports are emailed, and available on the PDFs page</em>
                              <%# only current_user's pdfs count for this report: %>
                              <% elsif report.users_pdf_count_for_this_report(current_user.id) > 0 %>
                                  <%= link_to "#{report.users_pdf_count_for_this_report(current_user.id)}", pdfs_path(id: report.id) %>
                              <% else %>
                                  none
                              <% end %>
                            </td>
                            <td>
                              <%# note: only allow HTML/PDF display if report is enabled and not an auto-run(cron) report %>
                              <% if report.auto_run_at.present? %>
                                  <%= report.auto_run_at_to_s %> <em>emailed report</em>
                              <% elsif report.enabled && report.auto_run_at.blank? %>
                                  <%= link_to 'HTML', report_listing_events_path(id: report.id, q: report.report_criteria) %>
                                  &nbsp;&nbsp;&nbsp;
                                  <%= link_to 'PDF', reports_pdf_path(id: report.id, format: :pdf) %>
                              <% else %>
                                  <em>disabled</em>
                              <% end %>
                              <%# note: owner or an admin may delete this report %>
                              <% if current_user.id == report.user_id || current_user.role?(:admin) %>
                                  &nbsp;&nbsp;&nbsp;
                                  <%= link_to 'Delete', report, confirm: "\n*** WARNING ***\n\nThis will also delete all PDF's created by this report.\n\nAre you sure?\n\n", method: :delete %>
                              <% else %>
                                  &nbsp;
                              <% end %>
                            </td>
                          </tr>
                      <% end %>
                  <% else %>
                    <tr><td colspan="6"><h3>No reports found!</h3></td></tr>
                  <% end %>
                </tbody>
              </table>
            </div> <!-- index_as_table -->
          </div> <!-- index_content -->
        </div> <!-- paginated_collection_contents -->
        <div id="index_footer">
          <%= will_paginate @reports %>
        </div> <!-- index_footer -->
      </div> <!-- paginated_collection -->
    </div> <!-- main_content -->
  </div> <!-- main_content_wrapper -->
</div> <!-- osprotect_content -->

app/views/reports/new.html.erb
<% if params[:commit] == 'create Incidents Report' || @report.report_type == 2 %>
  <% @title = 'New Incident Report' %>
  <%= render 'incidents_form' %>
<% else %>
<% @title = 'New Event Report' %>
  <%= render 'events_form' %>
<% end %>

app/views/reports/show.html.erb
<h1>access denied!</h1>